### ISSUE TITLE
Virtual method in the middle of hierarchy.

### ISSUE THREAD

**Issue by lordnn** [neoml-lib/neoml#28]
`CStratifiedCrossValidationSubProblem::GetVector` virtual method is not a member of interface, it's bad practice. And can be totally removed from class as not used.
